version: '3.2'

services:

  nodejs:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    image: sensorbox-nodejs
    container_name: sensorbox-nodejs
    volumes:
      - type: bind
        source: ./nodejs/
        target: /usr/share/app
    ports:
      - "8585:8585"
    command: "sh ./bin/startup.sh"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always

  vuejs:
    build:
      context: .
      dockerfile: docker/vuejs/Dockerfile
    image: sensorbox-vuejs
    container_name: sensorbox-vuejs
    volumes:
      - type: bind
        source: ./vuejs/
        target: /usr/share/app
    ports:
      - "9595:9595"
    command: "sh ./bin/startup.sh"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
    restart: always

  camera:
    build:
      context: .
      dockerfile: docker/camera/Dockerfile
    image: sensorbox-camera
    container_name: sensorbox-camera
    ports:
      - "8080:8080"
    restart: always
    command: "uv4l --driver raspicam --auto-video_nr --width 640 --height 480 --encoding jpeg"

volumes:
  mongodbvolume:
    driver: local
