const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const mongoose = require('mongoose')
mongoose.connect('mongodb://sensorbox-mongodb:27017/test')
var config = require('./config')
var mainRouter = require('./src/routes/MainRouter')
var supervisor = require('./src/scheduler/Supervisor')
supervisor.start()
const app = express()
app.use(bodyParser.urlencoded({ extended:true }))
app.use(bodyParser.json())
app.use(cors())
app.use('/', mainRouter)
app.listen(process.env.PORT || config.server.port)
console.log(`Listening on poort ${config.server.port}`)
process.on('uncaughtException', (error) => {
  console.log(error)
})
